[package]
name = "rsvk"
version = "0.1.0"
edition = "2021"

[dependencies]
xcb = { version = "1.1.1" }
vulkano = { version = "0.31.1" }
vulkano-shaders = { version = "0.31.1" }
bytemuck = { version = "1.12.1" }
libc = { version = "0.2.135" }

[features]
validation = []
api_dump = []
